### ISSUE TITLE
English Issues and Minor Improvements to Landing Page

### ISSUE THREAD

**Issue by rexliu3** [launchtechllc/site#1]
There are a few English issues and possible minor improvements in the descriptions on the landing page bolded below:

About Launch Tech
Launch Tech LLC is a SaaS (Software as a Service) product holding company, dedicated to launching real-world software applications. We create products that are useful, meaningful, and applicable to different people and different situations around the world, and we partner with other organizations to make this into a reality! **Previous sentence is a run-on sentence (3 "and")**

Though we are a SaaS product company, we try to open with our processes, builds, and deadlines. **(Error in "we try to open": meant to say "we try to be open")** We have a calendar that shares all of the things we're working on, and when certain events/product-builds will start, end, and be deployed. **Insert link to calendar here**

**In Contact Us! Section:**
Product Partnerships may be accidently bolded. If intentionally bolded, this does not fit well with the other bullet points.

**Comment by calixo888** [comment]
Thanks for the feedback @rexliu3! Just implemented
